In [1]:
#k is the number of neighbors
#k-nearest neighbors KNN default number of neighbors is 5 and should always be odd
#how KNN will be work with even numbers of neighbors ?

#KNN classification  works on modes (frequency of elementss) (categorical)
#KNN regression works on mean (continous/number i.e measured)

#In regression KNN just take an average
#Things controlled in algo is hyper parameter, n if not specified python take default

#(training data split) 70% training and 30% test data

#set seed is a predecided range random number generator 

#pandas ploting,graph, basically excel

#scilearn default ML lib

#scipy statistics package

#mathplotlib is visualization lib for ploting 

#dash based on d3 python lib



In [3]:
#
import numpy as np

l = [[1,2,3],[4,5,6],[7,8,9]]


In [4]:
array_1 = np.array(l)

In [5]:
array_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
type(array_1)

numpy.ndarray

In [7]:
array_1.shape

(3, 3)

In [8]:
array_1.T #need to assign as its temporily storaged

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [9]:
array_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
matrix_2 = [[1,2,3],[4,5,6]]

In [11]:
np.array(matrix_2).T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
arr = np.arange(1,11)

In [14]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr[1:-2:2] #slice

array([2, 4, 6, 8])

In [18]:
array_1[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [19]:
array_1.dtype

dtype('int64')

In [21]:
from numpy import genfromtxt
my_data = genfromtxt("/Users/03000070/Downloads/weather_small_2012.csv", delimiter=',')

In [25]:
# good way to do with numpy / import of csv
weather = np.genfromtxt("/Users/03000070/Downloads/weather_small_2012.csv", delimiter=',',skip_header=1)

#skip_header is used to skip number of rows to skip

In [26]:
weather

array([[   nan,  -1.8 ,  -3.9 , ...,   4.  ,   8.  , 101.24],
       [   nan,  -1.8 ,  -3.7 , ...,   4.  ,   8.  , 101.24],
       [   nan,  -1.8 ,  -3.4 , ...,   7.  ,   4.  , 101.26],
       ...,
       [   nan,  -0.5 ,  -1.5 , ...,  28.  ,   4.8 ,  99.95],
       [   nan,  -0.2 ,  -1.8 , ...,  28.  ,   9.7 ,  99.91],
       [   nan,   0.  ,  -2.1 , ...,  30.  ,  11.3 ,  99.89]])

In [27]:
weather.shape

(8784, 7)

In [28]:
weather[0]

array([   nan,  -1.8 ,  -3.9 ,  86.  ,   4.  ,   8.  , 101.24])

In [31]:
temperature = np.array(weather[:,1:2])

In [33]:
temperature

array([[-1.8],
       [-1.8],
       [-1.8],
       ...,
       [-0.5],
       [-0.2],
       [ 0. ]])

In [34]:
farenheit = (temperature * 9/5) + 32

In [35]:
farenheit

array([[28.76],
       [28.76],
       [28.76],
       ...,
       [31.1 ],
       [31.64],
       [32.  ]])

In [36]:
dew_point_temperature = np.array(weather[:,2:3])

In [37]:
dew_point_temperature

array([[-3.9],
       [-3.7],
       [-3.4],
       ...,
       [-1.5],
       [-1.8],
       [-2.1]])

In [38]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [39]:
a+b

array([ 6,  8, 10, 12])

In [40]:
print(temperature + dew_point_temperature)

[[-5.7]
 [-5.5]
 [-5.2]
 ...
 [-2. ]
 [-2. ]
 [-2.1]]


In [45]:
A = np.arange(1,10).reshape(3,3)

In [46]:
B = np.arange(11,20).reshape(3,3)

In [47]:
A/B

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [48]:
# temperature > 0 

temperature[temperature>0] #subseting element[element]

array([0.2, 0.8, 1.8, ..., 0.6, 0.1, 0.2])

In [49]:
#dew_points whose temperature >0

dew_point_temperature[temperature > 0]

array([-1.7, -1.1, -0.4, ..., -0.6, -2.7, -2.4])

In [53]:
#temperature >0 and below <10 multiple condition

temperature[(temperature>0) & (temperature < 10)]


array([0.2, 0.8, 1.8, ..., 0.6, 0.1, 0.2])

In [56]:
#max of temperature column

temperature.argmax() #return index
temperature.max() # return value

33.0

In [59]:
#min of temperatue col

temperature.min()

-23.3

In [60]:
#median

np.median(temperature)

9.3

In [61]:
a = np.arange(1,10).reshape(3,3)

In [62]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
a.shape

(3, 3)

In [64]:
a.ndim

2

In [103]:
#retain text in numpy array

diabetes = np.genfromtxt("/Users/03000070/Downloads/diabetes.csv", delimiter=",",dtype="U32")


In [104]:
diabetes

array([['pregnancies', 'glucose', 'diastolic', ..., 'dpf', 'age',
        'diabetes'],
       ['6', '148', '72', ..., '0.627', '50', '1'],
       ['1', '85', '66', ..., '0.35100000000000003', '31', '0'],
       ...,
       ['5', '121', '72', ..., '0.245', '30', '0'],
       ['1', '126', '60', ..., '0.349', '47', '1'],
       ['1', '93', '70', ..., '0.315', '23', '0']], dtype='<U32')

In [107]:
header = diabetes[0]

In [108]:
header

array(['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes'], dtype='<U32')

In [110]:
diabetes_without_header=np.genfromtxt("/Users/03000070/Downloads/diabetes.csv", delimiter=",",skip_header=1)

In [111]:
diabetes_without_header.dtype

dtype('float64')

In [119]:
sum(diabetes_without_header[:,-1:])

array([268.])

In [120]:
diabetes_without_header.shape

(768, 9)

In [121]:
#3 dimension array

#astype('type') to type cast in numpy pandas


In [123]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [122]:
np.zeros(5).shape

(5,)

In [124]:
reshap = np.array([1,2,3,4,5,6,7])

In [126]:
reshap.shape

(7,)

In [127]:
reshap.reshape(1,7)

array([[1, 2, 3, 4, 5, 6, 7]])

In [128]:
reshap.reshape(7,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [132]:
np.random.randn(10)

array([-0.12324312,  1.05284254, -0.22954493, -0.40454929, -1.36377802,
       -0.68326232, -0.27403666,  1.28399922,  0.72039525, -0.17000254])

In [133]:
np.random.rand(10)

array([0.01321238, 0.07578479, 0.07700678, 0.317424  , 0.77387945,
       0.78342728, 0.71034902, 0.67850544, 0.54155533, 0.70784466])

In [137]:
np.random.randint(1,10)

7

In [138]:
np.random.randint(1,10, size = 5 )

array([8, 4, 1, 7, 5])

In [143]:
np.random.seed(42)
np.random.randint(1,100, size = 50 )

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75, 88, 24,  3, 22, 53,  2, 88,
       30, 38,  2, 64, 60, 21, 33, 76, 58, 22, 89, 49, 91, 59, 42, 92, 60,
       80, 15, 62, 62, 47, 62, 51, 55, 64,  3, 51,  7, 21, 73, 39, 18])

In [149]:
A = np.random.randn(10)

B = np.random.randn(10)

In [150]:
np.add(A,B)

#or

A+B

array([-1.86537296,  2.03943209,  3.06934704,  0.55807998, -0.80291388,
        0.72000565, -1.54273415, -1.58882208,  0.54424996, -0.14879275])

In [151]:
A

array([-0.60025385,  0.94743982,  0.291034  , -0.63555974, -1.02155219,
       -0.16175539, -0.5336488 , -0.00552786, -0.22945045,  0.38934891])

In [152]:
B

array([-1.26511911,  1.09199226,  2.77831304,  1.19363972,  0.21863832,
        0.88176104, -1.00908534, -1.58329421,  0.77370042, -0.53814166])

In [153]:
C = np.random.randn(10)

In [154]:
C

array([-1.3466781 , -0.88059127, -1.1305523 ,  0.13442888,  0.58212279,
        0.88774846,  0.89433233,  0.7549978 , -0.20716589, -0.62347739])

In [155]:
np.maximum(A,B,C)

array([-0.60025385,  1.09199226,  2.77831304,  1.19363972,  0.21863832,
        0.88176104, -0.5336488 , -0.00552786,  0.77370042,  0.38934891])

In [ ]:
#Random walk concept